---

- hosts: localhost

  tasks:
    - name: Pull ansible script and resources from git
      git:
        repo: https://github.com/zztach/dev-machine-bootstrapper.git
        dest: "/tmp/dev-machine-bootstrapper"
        accept_hostkey: yes
        update: yes
        force: yes

    - name: git checkout PlayGround
      git:
        repo: git@bitbucket.org:zztach/playground.git
        dest: "/home/{{ ansible_env.USER }}/sources/Playground"
        accept_hostkey: yes
        update: yes
        force: yes

    - name: git checkout PythiaGP
      git:
        repo: git@bitbucket.org:zztach/pythiagp.git
        dest: "/home/{{ ansible_env.USER }}/sources/pythiagp"
        accept_hostkey: yes
        update: yes
        force: yes

    - name: git checkout clojure-webapp
      git:
        repo: git@bitbucket.org:zztach/clojure-webapp.git
        dest: "/home/{{ ansible_env.USER }}/sources/clojure-webapp"
        accept_hostkey: yes
        update: yes
        force: yes

    - name: git checkout cyclades-companion
      git:
        repo: git@bitbucket.org:zztach/cyclades-companion.git
        dest: "/home/{{ ansible_env.USER }}/sources/cyclades-companion"
        accept_hostkey: yes
        update: yes
        force: yes

    - name: git checkout OpenGL
      git:
        repo: git@bitbucket.org:zztach/opengl.git
        dest: "/home/{{ ansible_env.USER }}/sources/OpenGL"
        accept_hostkey: yes
        update: yes
        force: yes

    - name: git checkout Leaderboard
      git:
        repo: git@github.com:zztach/Leaderboard.git
        dest: "/home/{{ ansible_env.USER }}/sources/Leaderboard"
        accept_hostkey: yes
        update: yes
        force: yes

    - name: git checkout Dungeon
      git:
        repo: git@github.com:zztach/Dungeon.git
        dest: "/home/{{ ansible_env.USER }}/sources/Dungeon"
        accept_hostkey: yes
        update: yes
        force: yes

    - name: Pull ansible script and resources from git
      git:
        repo: https://github.com/zztach/dev-machine-bootstrapper.git
        dest: "/home/{{ ansible_env.USER }}/sources/dev-machine-bootstrapper"
        accept_hostkey: yes
        update: yes
        force: yes

    - name: Install vim
      become: true
      apt:
        name: vim
        state: present

    - name: Alias of vi to vim.tiny
      lineinfile:
        state: present
        destfile: "/home/{{ ansible_env.USER }}/.bashrc"
        line: 'alias vi=vim'

    - name: Create autostart folder
      file:
        path: /home/{{ ansible_env.USER }}/.config/autostart
        state: directory
        mode: 0755

    - name: Install Teamviewer
      become: true
      apt:
        deb: https://download.teamviewer.com/download/teamviewer_i386.deb
        state: present

    - name: Install g++
      become: true
      apt:
        name: g++
        state: present

    - name: Install CMake
      become: true
      apt:
        name: cmake
        state: present

    - name: Install SDL2
      become: true
      apt:
        name: libsdl2-dev
        state: present

    - name: Install OpenVPN
      become: true
      apt:
        name: openvpn
        state: present

    - name: Export LD_LIBRARY_PATH
      lineinfile:
        state: present
        destfile: "/home/{{ ansible_env.USER }}/.bashrc"
        line: 'export LD_LIBRARY_PATH=/usr/lib64'

    - name: Disable ipv6 \#1
      become: true
      sysctl:
        name: net.ipv6.conf.all.disable_ipv6
        value: 1
        sysctl_set: yes
        state: present

    - name: Disable ipv6 \#2
      become: true
      sysctl:
        name: net.ipv6.conf.default.disable_ipv6
        value: 1
        sysctl_set: yes
        state: present

    - name: Disable ipv6 \#3
      become: true
      sysctl:
        name: net.ipv6.conf.lo.disable_ipv6
        value: 1
        sysctl_set: yes
        state: present
        reload: yes

    - name: Deploy default .gitconfig
      copy:
       src: /tmp/dev-machine-bootstrapper/apps-conf-files/.gitconfig
       dest: /home/{{ ansible_env.USER }}/.gitconfig