---

- hosts: localhost
  connection: local

- name: Prerequisites
  include: common.yml

- name: Install development tools
  include: dev-tools.yml

- name: Install various software
  include: software.yml