---

- hosts: localhost
  connection: local
  vars:
    apps_dir: "/opt"
    jdk_folder_name: jdk1.8.0_144
    java_version: 8u144
    download_url: "http://download.oracle.com/otn-pub/java/jdk/8u144-b01/090f390dda5b47b9b721c7dfaa008135/jdk-{{ java_version }}-linux-x64.tar.gz"
    jdk_folder: "{{ apps_dir }}/{{ jdk_folder_name }}"
    java_archive: "jdk-{{ java_version }}-linux-x64.tar.gz"
    idea_version: 2017.2.3
    clion_version: 2017.2.2

  tasks:
   - name: Add Tilix repository
     become: true
     apt_repository:
       repo: 'ppa:webupd8team/terminix'

   - name: Install the package "Tilix"
     become: true
     apt:
       name: tilix
       state: present
   
   - name: Pull ansible script and resources from git
     git:
       repo: https://github.com/zztach/dev-machine-bootstrapper.git
       dest: "/tmp/dev-machine-bootstrapper"
       update: yes
       force: yes

   - name: Install the package "dconf-cli" for importing Tilix settings
     become: true
     apt:
       name: dconf-cli
       state: present

   - name: Restore tilix configuration
     shell: dconf load /com/gexperts/Tilix/ < /tmp/dev-machine-bootstrapper/apps-conf-files/tilix/tilix.conf

   - name: Check VirtualGL path under /opt
     stat: path="/{{ apps_dir }}/VirtualGL-2.5.2"
     register: virtualgl_path

   - name: Download VirtualGL and extract under /opt
     become: true
     unarchive:
       src: https://github.com/VirtualGL/virtualgl/releases/download/2.5.2test/VirtualGL-2.5.2.tar.gz
       dest: "{{ apps_dir }}"
       remote_src: True
     when: not virtualgl_path.stat.exists

   - name: Check glew path under /opt
     stat: path="/{{ apps_dir }}/glew-1.11.0"
     register: glew_path

   - name: Download GLEW and extract under /opt
     become: true
     unarchive:
       src: https://sourceforge.net/projects/glew/files/glew/1.11.0/glew-1.11.0.zip/download
       dest: "{{ apps_dir }}"
       remote_src: True
     when: not glew_path.stat.exists

   - name: Check glm path under /opt
     stat: path="/{{ apps_dir }}/glm"
     register: glm_path

   - name: Download GLM and extract under /opt
     become: true
     unarchive:
       src: https://sourceforge.net/projects/ogl-math/files/glm-0.9.4.6/glm-0.9.4.6.zip/download
       dest: "{{ apps_dir }}"
       remote_src: True
     when: not glm_path.stat.exists

   - name: Check for IDEA folder 
     become: true
     find:
       paths: "/{{ apps_dir }}/idea-IU-172.3968.16"       
     register: idea_folders

   - name: ideamsg
     debug:
       var: idea_folders

   - name: Download IntelliJ Idea and extract under /opt
     become: true
     unarchive:
       src: "https://download.jetbrains.com/idea/ideaIU-{{ idea_version }}.tar.gz"
       dest: "{{ apps_dir }}"
       remote_src: True
     when: idea_folders.matched == 0

   - name: Check for CLion folder
     find:
       paths: "/{{ apps_dir }}/clion-2017.2.2/"       
     register: clion_folders

   - name: Download CLion and extract under /opt
     become: true
     unarchive:
       src: "https://download.jetbrains.com/cpp/CLion-{{ clion_version }}.tar.gz"
       dest: "{{ apps_dir }}"
       remote_src: True
     when: clion_folders.matched == 0

   - name: Check for Sublime folder
     find:
       paths: "{{ apps_dir }}/sublime_text_3"       
     register: sublime_folders

   - name: testsub
     debug:
       var: sublime_folders

   - name: Download SublimeText and extract under /opt
     become: true
     unarchive:
       src: https://download.sublimetext.com/sublime_text_3_build_3126_x64.tar.bz2
       dest: "{{ apps_dir }}"
       remote_src: True
     when: sublime_folders.matched == 0

   - name: Check for Java folder
     find:
       paths: "{{ apps_dir }}/jdk1.8.0_144"       
     register: jdk_folders

   - name: testjdk
     debug:
       var: jdk_folders

   - name: Download Java
     become: true    
     command: "curl -L -b \"oraclelicense=a\" {{ download_url }} -O -o {{ apps_dir }}"
     when: jdk_folders.matched == 0

   - name: Unpack archive
     become: true
     unarchive:
       src: "{{ java_archive }}"
       dest: "{{ apps_dir }}"
     when: jdk_folders.matched == 0

   - name: Fix ownership
     become: true
     file: state=directory path={{ jdk_folder }} owner={{ ansible_env.USER }} group={{ ansible_env.USER }} recurse=yes

   - name: Clean up
     become: true
     file: state=absent path={{ java_archive }}

   - name: Update .bashrc with JAVA_HOME
     lineinfile:
       state: present
       regexp: 'JAVA_HOME'
       destfile: "/home/{{ ansible_env.USER }}/.bashrc"
       line: 'export JAVA_HOME=/opt/{{ jdk_folder }}'
     when: jdk_folders | length == 0

   - name: Alias of vi to vim.tiny
     lineinfile:
       state: present
       destfile: "/home/{{ ansible_env.USER }}/.bashrc"
       line: 'alias vi=vim.tiny'

   - name: Check if Steam already installed
     shell: apt list --installed | grep steam
     ignore_errors: True
     register: is_steam_installed
  
   - name: asdsad
     debug:
       var: is_steam_installed.stdout

   - name: Install Steam
     become: true
     apt:
       deb: https://steamcdn-a.akamaihd.net/client/installer/steam.deb
       state: present
     when: is_steam_installed.stdout | length == 0

   - name: Check if WPS already installed
     shell: dpkg --get-selections | grep wps-office
     ignore_errors: True
     register: is_wps_installed

   - name: Install WPS
     become: true
     apt:
       deb: http://kdl1.cache.wps.com/ksodl/download/linux/a21//wps-office_10.1.0.5707~a21_amd64.deb
       state: present
     when: is_wps_installed.stdout | length == 0

   - name: Install VLC
     become: true
     apt:
       name: vlc
       state: latest

   - name: Install Parcellite
     become: true
     apt:
       name: parcellite
       state: latest

   - name: Install conky
     become: true
     apt:
       name: conky-all
       state: latest

   - name: Apply conky configuration     
     copy:
       src: /tmp/dev-machine-bootstrapper/apps-conf-files/conky/
       dest: /home/{{ ansible_env.USER }}/.conky     

   - name: Apply +x permissions to conky startup script     
     file:
       path: /home/{{ ansible_env.USER }}/.conky/conky-startup.sh
       owner: "{{ ansible_env.USER }}"
       group: "{{ ansible_env.USER }}"
       mode: "u=rwx,g=r,o=r"

   - name: Add Conky to startup 
     become: true
     copy:
       src: /tmp/dev-machine-bootstrapper/apps-conf-files/conky/Conky.desktop
       dest: /home/{{ ansible_env.USER }}/.config/autostart/Conky.desktop     

   - name: Install indicator-multiload
     become: true
     apt:
       name: indicator-multiload
       state: latest
   
   - name: Install cairo-dock
     become: true
     apt:
       name: cairo-dock
       state: latest

   - name: Apply cairo-dock configuration     
     copy:
       src: /tmp/dev-machine-bootstrapper/apps-conf-files/cairo/
       dest: /home/{{ ansible_env.USER }}/.config/cairo-dock     

   - name: Add Cairo to startup 
     become: true
     copy:
       src: /tmp/dev-machine-bootstrapper/apps-conf-files/cairo/CairoDock.desktop
       dest: /home/{{ ansible_env.USER }}/.config/autostart/CairoDock.desktop    

   - name: Check for Sublime folder
     find:
       paths: "{{ apps_dir }}/amdgpu-pro-17.30-465504"       
     register: amdgpu_folders

   - name: Check if amdgpu driver already installed
     shell: dpkg --get-selections | grep amdgpu-pro
     ignore_errors: True
     register: is_amdgpu_installed

   - name: Download amdgpu pro driver
     command: "wget https://www2.ati.com/drivers/linux/ubuntu/amdgpu-pro-17.30-465504.tar.xz -O /home/{{ ansible_env.USER }}/Downloads/amdgpu-pro-17.30-465504.tar.xz --referer=http://www2.ati.com"                    
     when: amdgpu_folders.matched == 0

   - name: Extract amdgpu pro driver
     become: true
     unarchive:
       src: /home/{{ ansible_env.USER }}/Downloads/amdgpu-pro-17.30-465504.tar.xz
       dest: "{{ apps_dir }}"
       remote_src: True
     when: amdgpu_folders.matched == 0

   - name: Install amd-gpu driver 
     become: true
     command: "{{ apps_dir }}/amdgpu-pro-17.30-465504/amdgpu-pro-install -y"                    
     when: is_amdgpu_installed.stdout | length == 0   

   - name: Fix ownership
     become: true
     file: state=directory path={{ apps_dir }}/clion-{{ clion_version }} owner={{ ansible_env.USER }} group={{ ansible_env.USER }} recurse=yes

   - name: Fix ownership
     become: true
     file: state=directory path={{ apps_dir }}/idea-IU-172.3968.16 owner={{ ansible_env.USER }} group={{ ansible_env.USER }} recurse=yes
  
   - name: Fix ownership
     become: true
     file: state=directory path={{ apps_dir }}/amdgpu-pro-17.30-465504 owner={{ ansible_env.USER }} group={{ ansible_env.USER }} recurse=yes

   - name: Fix ownership
     become: true
     file: state=directory path={{ apps_dir }}/sublime_text_3 owner={{ ansible_env.USER }} group={{ ansible_env.USER }} recurse=yes

   - name: Fix ownership
     become: true
     file: state=directory path={{ apps_dir }}/VirtualGL-2.5.2 owner={{ ansible_env.USER }} group={{ ansible_env.USER }} recurse=yes

   - name: Fix ownership
     become: true
     file: state=directory path={{ apps_dir }}/kingsoft owner={{ ansible_env.USER }} group={{ ansible_env.USER }} recurse=yes

   - name: Fix ownership
     become: true
     file: state=directory path={{ apps_dir }}/glm owner={{ ansible_env.USER }} group={{ ansible_env.USER }} recurse=yes

   - name: Fix ownership
     become: true
     file: state=directory path={{ apps_dir }}/glew-1.11.0 owner={{ ansible_env.USER }} group={{ ansible_env.USER }} recurse=yes