---

- hosts: localhost
  connection: local

- name: Common tasks
  include: common.yml

- name: Install development tools
  include: dev-tools.yml

- name: Install development tools
  include: software.yml