---
# tasks file for glew
- name: Check glew path under /opt
  stat: path="/{{ apps_dir }}/glew-1.11.0"
  register: glew_path

- name: Download GLEW and extract under /opt
  become: true
  unarchive:
    src: https://sourceforge.net/projects/glew/files/glew/1.11.0/glew-1.11.0.zip/download
    dest: "{{ apps_dir }}"
    remote_src: True
  when: not glew_path.stat.exists

- name: Fix ownership
  become: true
  file: state=directory path={{ apps_dir }}/glew-1.11.0 owner={{ ansible_env.USER }} group={{ ansible_env.USER }} recurse=yes

